// ============================================================
// BayuOne — Database row ↔ application object converters
// ============================================================
// Amendment 4: added `description` field.
// Phase 3A: added photo_1..photo_6 and youtube_1..youtube_6.
// ============================================================

export function appFromRow(r) {
    return {
        id: r.id,
        slug: r.slug,
        type: r.type,
        title: r.title,
        name: r.name,
        org: r.org,
        email: r.email,
        phone: r.phone,
        location: r.location,
        mode: r.mode,
        category: r.category,
        date: r.date,
        url: r.url,
        urlButton: r.url_button,
        approval: r.approval,
        validity: r.validity,
        tarikhDari: r.tarikh_dari,
        tarikhSehingga: r.tarikh_sehingga,
        label: r.label,
        remark: r.remark,
        statusPenangguhan: r.status_penangguhan,
        statusPenangguhanSub: r.status_penangguhan_sub,
        photo: r.photo,
        hargaYuran: r.harga_yuran,
        feeType: r.fee_type,
        expertise: r.expertise || [],
        certs: r.certs || [],
        certCustom: r.cert_custom,
        niche: r.niche,
        summary: r.summary,
        description: r.description,
        dateEnd: r.date_end,
        isOneDay: r.is_one_day || false,
        hargaMin: r.harga_min,
        hargaMax: r.harga_max,
        penganjur: r.penganjur,
        // Phase 3A: Portfolio
        photo_1: r.photo_1,
        photo_2: r.photo_2,
        photo_3: r.photo_3,
        photo_4: r.photo_4,
        photo_5: r.photo_5,
        photo_6: r.photo_6,
        youtube_1: r.youtube_1,
        youtube_2: r.youtube_2,
        youtube_3: r.youtube_3,
        youtube_4: r.youtube_4,
        youtube_5: r.youtube_5,
        youtube_6: r.youtube_6
    };
}

export function rowFromApp(a) {
    return {
        id: a.id,
        slug: a.slug,
        type: a.type,
        title: a.title,
        name: a.name,
        org: a.org,
        email: a.email,
        phone: a.phone,
        location: a.location,
        mode: a.mode,
        category: a.category,
        date: a.date,
        url: a.url,
        url_button: a.urlButton,
        approval: a.approval,
        validity: a.validity,
        tarikh_dari: a.tarikhDari,
        tarikh_sehingga: a.tarikhSehingga,
        label: a.label,
        remark: a.remark,
        status_penangguhan: a.statusPenangguhan,
        status_penangguhan_sub: a.statusPenangguhanSub,
        photo: a.photo,
        harga_yuran: a.hargaYuran,
        fee_type: a.feeType,
        expertise: a.expertise || [],
        certs: a.certs || [],
        cert_custom: a.certCustom,
        niche: a.niche,
        summary: a.summary,
        description: a.description,
        date_end: a.dateEnd,
        is_one_day: a.isOneDay || false,
        harga_min: a.hargaMin,
        harga_max: a.hargaMax,
        penganjur: a.penganjur,
        // Phase 3A: Portfolio
        photo_1: a.photo_1,
        photo_2: a.photo_2,
        photo_3: a.photo_3,
        photo_4: a.photo_4,
        photo_5: a.photo_5,
        photo_6: a.photo_6,
        youtube_1: a.youtube_1,
        youtube_2: a.youtube_2,
        youtube_3: a.youtube_3,
        youtube_4: a.youtube_4,
        youtube_5: a.youtube_5,
        youtube_6: a.youtube_6
    };
}
